name: YangsechanGame
version: 0.0
main: dotori.muuk.yangsechan.Main
api-version: 1.19

commands:
  양세찬게임:
    description: 양세찬 게임을 시작합니다.
    usage: /<command>
  정답:
    description: 정답을 외칩니다.
    usage: /<command>
  yadmin:
    description: 양세찬 게임 관리자용 명령어입니다.
    usage: /<command> [subcommand]
    permission: yangsechan.admin
  doridori: